name: IBM Cloud Auto Update

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  ibm-cloud-update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        n
        EOF
    - name: Target IBM Cloud
      env:
        RESOURSE_ID: ${{ secrets.RESOURSE_ID }}
      run: |
        ibmcloud target -g "$RESOURSE_ID"
        ibmcloud target --cf
        ibmcloud cf install -v 6.51.0
    - name: Update IBM Cloud
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
        IBM_MEM_SIZE: ${{ secrets.IBM_MEM_SIZE }}
      run: |
        chmod +x upgrade-actions.sh
        ./upgrade-actions.sh